name: Auto Assign Issues to Project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  push:
    branches-ignore:
      - master

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action
        with:
          root: devops_lifecycle_implementation/website/
